### ISSUE TITLE
Bold the currently selected item in the move list.

### ISSUE THREAD

**Issue by thdk** [thdk/react-tictactoe#2]
Bold the currently selected item in the move list.

**Comment by thdk** [comment]
@jovdb any thought about this?
`<Move key={move} index={move} description={desc} onClick={() => this.jumpTo(move)} coors={coors} isSelected={move === this.state.stepNumber}/>`

This looks so dirty...

**Comment by jovdb** [comment]
This is the normal syntax.
You can also use the object spread operator in TSX which can increase
readability. You could create a moveProps object and pass it wich object
spread syntax to the Move component.

my remarks:
- key is normally used in a loop
- it is not clear to me what 'move' is: indexToMove?
- onClick contains a lambda, which will make this component dirty at each
render. But for this small test project, it will probably not matter.

Op wo 15 nov. 2017 09:48 schreef Thomas Dekiere <notifications@github.com>:

**Comment by thdk** [comment]
Merged into master
